Algoritmo "Problema crescente"

Var
      x,y:inteiro


Inicio
      escrevaL("Digite dois numeros: ")
      leia(x)
      leia(y)
      
      enquanto x<>y faca
     se  x < y  entao
       escreval(" CRESCENTE ")
       
       senao
       escrevaL(" DECRESCENTE ")
       fimse
       
       
       escreval("Digite outros dois numeros: ")
       leia(x)
       leia(y)
       
       fimenquanto


Fimalgoritmo